name: peakinspector
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cycler=0.10.0
  - dbus=1.13.6
  - et_xmlfile=1.0.1
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=58.2
  - jdcal=1.4.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - ncurses=6.2
  - numpy=1.19.5
  - olefile=0.46
  - openpyxl=3.0.7
  - openssl=1.1.1j
  - pandas=1.1.5
  - pcre=8.44
  - pillow=8.1.1
  - pip=21.0.1
  - pthread-stubs=0.4
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.7
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2021.1
  - qt=5.9.7
  - qtpy=1.9.0
  - readline=7.0
  - scipy=1.5.3
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.28.0
  - tk=8.6.10
  - tornado=6.1
  - wheel=0.36.2
  - xlsxwriter=1.3.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8

